[package]
name = "networking"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
shared_types = { path = "../shared_types" }
log = { workspace = true }
thiserror = { workspace = true }
